export default {
	child:"https://elm.cangdu.org/v1/cities",//获取城市列表
	search:"https://elm.cangdu.org/v1/pois",//搜索接口
	city:"https://elm.cangdu.org/v2/pois/",//详细地址
	fenlei:"https://elm.cangdu.org/v2/index_entry",//商品分类
	shop:"https://elm.cangdu.org/shopping/restaurants",//附近商家
	searchshop:"https://elm.cangdu.org/v4/restaurants",//搜索餐馆
	zhongxi:"https://elm.cangdu.org/v3/profile/explain",//服务中心
	login:"https://elm.cangdu.org/v2/login",//登录
	xiangxi:"https://elm.cangdu.org/shopping/v2/menu?restaurant_id=",//商品详情
	xiangqing:"https://elm.cangdu.org/shopping/restaurant/",//商家详情
	addshop:"https://elm.cangdu.org/v1/carts/checkout",//加入购物车
	evaluate:"https://elm.cangdu.org/ugc/v2/restaurants/",//评价的分数
	addressmessage:"https://elm.cangdu.org/v1/users/",//获取用户收货地址列表
	addressadd:"https://elm.cangdu.org/v1/users/",//添加收货地址
	deleaddress:"http://elm.cangdu.org/v1/users/",//删除收货地址
	xiadan:"https://elm.cangdu.org/v1/users/",//下单
	dingdanlist:"https://elm.cangdu.org/bos/v2/users/",//订单列表
	sponsored:"https://elm.cangdu.org/promotion/v2/users/",//红包
}