import loadable from '@/utils/loader'
export const Home = loadable(() => import('@/pages/home'))
export const Login = loadable(() => import('@/pages/login'))
export const Choosechild = loadable(() => import('@/pages/choosechild'))
export const Pageone = loadable(() => import('@/components/pageone'))
export const Product = loadable(() => import('@/components/product'))
export const Productone = loadable(() => import('@/components/productone'))
export const Producttwo = loadable(() => import('@/components/producttwo'))
export const Pagetwo = loadable(() => import('@/components/pagetwo'))//第二个页面
export const Pagethree = loadable(() => import('@/components/pagethree'))//第三个页面
export const Pagefour = loadable(() => import('@/components/pagefour'))//第四个页面
export const Logindefs = loadable(() => import('@/components/login'))//登录页面
export const Download = loadable(() => import('@/components/download'))//下载页面
export const Details = loadable(() => import('@/components/details'))//商家详情
export const Service = loadable(() => import('@/components/service'))//下载页面
export const Shopone = loadable(() => import('@/components/shopone'))//单个商品信息介绍页面
export const Fu = loadable(() => import('@/components/fu'))//下载页面
export const Balance = loadable(() => import('@/components/balance'))//下载页面
export const Personal = loadable(() => import('@/components/personal'))//账户信息
export const Modify = loadable(() => import('@/components/modify'))//修改用户名
export const CreateGoods = loadable(() => import('@/components/createGoods'))//收货地址
export const Placingaddress = loadable(() => import('@/components/placingaddress'))//收货地址下单页面
export const Address = loadable(() => import('@/components/address'))//收货地址menber
export const Menber = loadable(() => import('@/components/menber'))//会员
export const Meming = loadable(() => import('@/components/meming'))//会员说明
export const Buy = loadable(() => import('@/components/buy'))//会员购买
export const Exchange = loadable(() => import('@/components/exchange'))//兑换
export const Remarks = loadable(() => import('@/components/remarks'))//备注页面
export const Pay = loadable(() => import('@/components/pay'))//支付页面
export const Preferential = loadable(() => import('@/components/preferential'))//红包
export const Preferential_left = loadable(() => import('@/components/preferential_left'))//红包1
export const Preferential_right = loadable(() => import('@/components/preferential_right'))//红包2
export const Placing = loadable(() => import('@/components/placing'))//下单页面
export const DescriptionThe = loadable(() => import('@/components/descriptionThe'))//红包说明
export const Integral = loadable(() => import('@/components/integral'))//红包说明